packages:
  - name: main
    actions:
      - name: n2w
        # environment:
        #   WA_KING_ODATA_TENANTID: "${WA_KING_ODATA_TENANTID}"
        #   WA_KING_ODATA_CLIENTID: "${WA_KING_ODATA_CLIENTID}"
        #   WA_KING_ODATA_CLIENTSECRET: "${WA_KING_ODATA_CLIENTSECRET}"
        #   WA_KING_ODATA_CLIENTRESOURCE: "${WA_KING_ODATA_CLIENTRESOURCE}"
        #   WA_KING_ODATA_SERVICEURL: "${WA_KING_ODATA_SERVICEURL}"
        #   WA_KING_ODATA_SERVICESUBKEY: "${WA_KING_ODATA_SERVICESUBKEY}"